export enum ReadOnlyCauseEnum {
  None = 0,
  Rank = 1,
  SuboperationPrimaryFeedRules = 2,
  SuboperationFlankFeedRules = 3,
  SuboperationDepthOfCutRules = 4,
  RoundInsertProduct = 5,
  SurfaceRoughnessesMdmProductValidation = 6,
  SolidMillingWorkingEngagementCorrectionMdmProductValidation = 7,
  MaximumOfEngagementMdmProductValidation = 8,
  IndexableMillingWorkingEngagementCorrectionMdmProductValidation = 9,
  SolidDrillingInsertIndexCountMdmProductValidation = 10,
  AermxCorrectionMdmProductValidation = 11,
  RgfNormgxMdmProductValidation = 12,
  KaprTypeNotSelected = 13,
  LabelTypeDrilXxdNotSelected = 14,
  SuboperationRankingValidation = 15,
  MDMProductSubopValidation = 16,
  SuboperationFeedAxialRules = 17,
}
