export const SVG_ICONS = [
    { name: 'home', path: 'home.svg' },
    { name: 'help', path: 'help.svg' },
    { name: 'envelope', path: 'envelope.svg' },
    { name: 'user', path: 'user.svg' },
    { name: 'newspaper', path: 'newspaper.svg' },
    { name: 'question-circle', path: 'question-circle.svg' },
    { name: 'info-circle', path: 'info-circle.svg' },
    { name: 'exclamation-circle', path: 'exclamation-circle.svg' },
    { name: 'exclamation-triangle', path: 'exclamation-triangle.svg' },
    { name: 'pencil-square', path: 'pencil-square.svg' },
    { name: 'caret-down', path: 'caret-down.svg' },
    { name: 'caret-up', path: 'caret-up.svg' },
    { name: 'warning', path: 'warning.svg' },
    { name: 'refresh', path: 'refresh.svg' },
    { name: 'lock', path: 'lock.svg' },
    { name: 'book', path: 'book.svg' },
    { name: 'circle', path: 'circle.svg' },
    { name: 'arrow-moving-away', path: 'arrow-moving-away.svg'},
    { name: 'pencil', path: 'pencil.svg' },
    { name: 'close', path: 'close.svg' },
    { name: 'floppy-o', path: 'floppy-o.svg' },
    { name: 'trash', path: 'trash.svg' },
    { name: 'plus', path: 'plus.svg' },
    { name: 'arrows-left-right-solid', path: 'arrows-left-right-solid.svg'},
    { name: 'list', path: 'list.svg'},
    { name: 'file-text-o', path: 'file-text-o.svg'},
]