export const CD2C_VALIDATION = {
  Feed: 'Feed',
  Cd2cValidationCapacityDataEnum_1: 'Ranking',
  Cd2cValidationCapacityDataEnum_2: 'Working Condition',
  Cd2cValidationCapacityDataEnum_3: 'Cutting Force',
  Cd2cValidationCapacityDataEnum_4: 'Depth Of Cut',
  Cd2cValidationCapacityDataEnum_5: 'Chip Thickness',
  Cd2cValidationCapacityDataEnum_10: 'Cutting Angle',
  Cd2cValidationCapacityDataEnum_11: 'Relative Engagement',
  Cd2cValidationCapacityDataEnum_12: 'Infeed',
  Cd2cValidationCapacityDataEnum_13: 'Feed Factor',
  Cd2cValidationCapacityDataEnum_14: 'Primary Feed',
  Cd2cValidationCapacityDataEnum_15: 'Flank Feed',
  Cd2cValidationCapacityDataEnum_16: 'Cutting Speed Correction',
  Cd2cValidationCapacityDataEnum_17: 'Tool Life Correction',
  Cd2cValidationCapacityDataEnum_18: 'Stability Correction',
  Cd2cValidationCapacityDataEnum_19: 'Coolant CVC',
  Cd2cValidationCapacityDataEnum_20: 'FeedNom Factor',
  Cd2cValidationCapacityDataEnum_21: 'Drilling Ratio Limit',
  Cd2cValidationCapacityDataEnum_22: 'Engagement Correction',
  Cd2cValidationCapacityDataEnum_23: 'Working Engagement Correction',
  Cd2cValidationCapacityDataEnum_24: 'Ramping Correction',
  Cd2cValidationCapacityDataEnum_25: 'Chip Space Correction',
  Cd2cValidationCapacityDataEnum_26: 'Tool Life Exponent',
  Cd2cValidationCapacityDataEnum_27: 'Stress Correction',
  Cd2cValidationCapacityDataEnum_28: 'Chip Thickness Correction',
  Cd2cValidationCapacityDataEnum_29: 'Maximum Stress',
  Cd2cValidationCapacityDataEnum_30: 'Feed',
  Cd2cValidationCapacityDataEnum_31: 'Diameter Feed',
  Cd2cValidationCapacityDataEnum_32: 'Surface Roughness',
  Cd2cValidationCapacityDataEnum_33: 'Coolant Tool Life Correction',
  Cd2cValidationCapacityDataEnum_34: 'Geometry Feed',
  Cd2cValidationCapacityDataEnum_35: 'Grade Feed',
  Cd2cValidationCapacityDataEnum_36: 'Capacity Data Overlap',
  Cd2cValidationCapacityDataEnum_37: 'Number of insert index',
  Cd2cValidationCapacityDataEnum_38: 'Feed force correction',
  Cd2cValidationCapacityDataEnum_39: 'Advance operations',
  Cd2cValidationCapacityDataEnum_40: 'Maximum value of Max Engagement',
  Cd2cValidationCapacityDataEnum_41: 'Max Working Engagement Ratio',
  Cd2cValidationCapacityDataEnum_42: 'Maximum Correction of Chip Thickness',
  Cd2cValidationCapacityDataEnum_43: 'Start Values',
  Cd2cValidationCapacityDataEnum_44: 'First Choice',
  Cd2cValidationCapacityDataEnum_45: 'Release Product',
  Cd2cValidationCapacityDataEnum_46: 'Non Rotating Drilling',
  Cd2cValidationCapacityDataEnum_47: 'AERMX Correction',
  Cd2cValidationCapacityDataEnum_48: 'Operation Type (CTPT)',
  Cd2cValidationCapacityDataEnum_49: 'Regrinding parameters',
  Cd2cValidationCapacityDataEnum_50: 'Regrinding parameters',
  Cd2cValidationCapacityDataEnum_51: 'Suboperations',
  Cd2cValidationCapacityDataEnum_52: 'Suboperations',
  Cd2cValidationCapacityDataEnum_53: 'Suboperations',
  Cd2cValidationCapacityDataEnum_54: 'Recommended Infeed Methods',
  Cd2cValidationCapacityDataEnum_55: 'Feed Factors',
  Cd2cValidationCapacityDataEnum_56: 'Feed Factors',
  Cd2cValidationCapacityDataEnum_57: 'Strategy',
  Cd2cValidationCapacityDataEnum_58: 'First Choice Management',
  Cd2cValidationCapacityDataEnum_59: 'Kapr',
  Cd2cValidationCapacityDataEnum_6: 'Suboperation',
  Cd2cValidationCapacityDataEnum_60: 'Kapr 2',
  Cd2cValidationCapacityDataEnum_61: 'Kapr 3',
  Cd2cValidationCapacityDataEnum_62: 'Kapr 4',
  Cd2cValidationCapacityDataEnum_63: 'Solid Drilling Feed Label Factor',
  Cd2cValidationCapacityDataEnum_64: 'Solid Drilling Grade Speed Factor',
  Cd2cValidationCapacityDataEnum_65: 'Indexable Drilling Feed Label Factor',
  Cd2cValidationCapacityDataEnum_66: 'Indexable Drilling Grade Speed Factor',
  Cd2cValidationCapacityDataEnum_67: 'OptiThread Rank',
  Cd2cValidationCapacityDataEnum_68: 'Suboperation',
  Cd2cValidationCapacityDataEnum_69: 'Step over ratio',
  Cd2cValidationCapacityDataEnum_7: 'Cutting Speed',
  Cd2cValidationCapacityDataEnum_70: 'Solid Milling Tool Life Correction',
  Cd2cValidationCapacityDataEnum_71: 'Solid Milling Cutting Speed Correction',
  Cd2cValidationCapacityDataEnum_72: 'Diameter Suboperation',
  Cd2cValidationCapacityDataEnum_73: 'Diameter Feed Axial',
  Cd2cValidationCapacityDataEnum_74: 'Pecking Pattern Strategy',
  Cd2cValidationCapacityDataEnum_75: 'Entering Angle',
  Cd2cValidationCapacityDataEnum_8: 'Tool Life',
  Cd2cValidationCapacityDataEnum_9: 'Coolant Ranking',
  Cd2cValidationMessageTypeEnum_1: 'missing data',
  Cd2cValidationMessageTypeEnum_2: 'no overlap',
  Cd2cValidationMessageTypeEnum_3: 'no overlap',
  Cd2cValidationMessageTypeEnum_4: 'no overlap',
  Cd2cValidationMessageTypeEnum_5: 'no overlap',
  Cd2cValidationMessageTypeEnum_6: 'no overlap',
};
